#ifndef "0-putchar.c"
#define "0-putchar.c"
#ifndef "1-alphabet.c"
#define "1-alphabet.c"
#ifndef "2-print_alphabet_x10.c"
#define "2-print_alphabet_x10.c"
#ifndef "3-islower.c"
#define "3-islower.c"
#ifndef "4-isalpha.c"
#define "4-isalpha.c"
#ifndef "5-sign.c"
#define "5-sign.c"
#ifndef "6-abs.c"
#define "6-abs.c"
#ifndef "_putchar.c"
#define "_putchar.c"
#endif
